import { Permissions, Units, Activities } from "./Constants";
declare type PermissionOptions = {
    read: (keyof typeof Permissions)[];
    write: (keyof typeof Permissions)[];
};
declare type WorkoutOptions = {
    type: keyof typeof Activities;
    startDate: Date;
    endDate: Date;
    duration?: number;
    energyBurned?: {
        unit: keyof typeof Units;
        value: number;
    };
    distance?: {
        unit: keyof typeof Units;
        value: number;
    };
};
declare enum AuthorizationStatus {
    NotDetermined = 0,
    SharingDenied = 1,
    SharingAuthorized = 2
}
declare const HealthKit: {
    isAvailable: () => Promise<boolean>;
    init: (options: PermissionOptions) => Promise<true>;
    saveWorkout: (options: WorkoutOptions) => Promise<string>;
    getAuthStatus: (options: PermissionOptions) => Promise<{
        read: AuthorizationStatus[];
        write: AuthorizationStatus[];
    }>;
};
export declare const HKConstants: {
    Permissions: {
        ActiveEnergyBurned: string;
        AppleExerciseTime: string;
        BasalEnergyBurned: string;
        BiologicalSex: string;
        BloodGlucose: string;
        BloodPressureDiastolic: string;
        BloodPressureSystolic: string;
        BodyFatPercentage: string;
        BodyMass: string;
        BodyMassIndex: string;
        BodyTemperature: string;
        DateOfBirth: string;
        Biotin: string;
        Caffeine: string;
        Calcium: string;
        Carbohydrates: string;
        Chloride: string;
        Cholesterol: string;
        Copper: string;
        EnergyConsumed: string;
        FatMonounsaturated: string;
        FatPolyunsaturated: string;
        FatSaturated: string;
        FatTotal: string;
        Fiber: string;
        Folate: string;
        Iodine: string;
        Iron: string;
        Magnesium: string;
        Manganese: string;
        Molybdenum: string;
        Niacin: string;
        PantothenicAcid: string;
        Phosphorus: string;
        Potassium: string;
        Protein: string;
        Riboflavin: string;
        Selenium: string;
        Sodium: string;
        Sugar: string;
        Thiamin: string;
        VitaminA: string;
        VitaminB12: string;
        VitaminB6: string;
        VitaminC: string;
        VitaminD: string;
        VitaminE: string;
        VitaminK: string;
        Zinc: string;
        Water: string;
        DistanceCycling: string;
        DistanceWalkingRunning: string;
        FlightsClimbed: string;
        HeartRate: string;
        Height: string;
        LeanBodyMass: string;
        MindfulSession: string;
        NikeFuel: string;
        RespiratoryRate: string;
        SleepAnalysis: string;
        StepCount: string;
        Steps: string;
        Weight: string;
        Workout: string;
    };
    Units: {
        bpm: string;
        calorie: string;
        celsius: string;
        count: string;
        day: string;
        fahrenheit: string;
        foot: string;
        gram: string;
        hour: string;
        inch: string;
        joule: string;
        meter: string;
        mgPerdL: string;
        mile: string;
        minute: string;
        mmhg: string;
        mmolPerL: string;
        percent: string;
        pound: string;
        second: string;
    };
    Activities: {
        AmericanFootball: string;
        Archery: string;
        AustralianFootball: string;
        Badminton: string;
        Baseball: string;
        Basketball: string;
        Bowling: string;
        Boxing: string;
        Climbing: string;
        Cricket: string;
        CrossTraining: string;
        Curling: string;
        Cycling: string;
        Dance: string;
        Elliptical: string;
        EquestrianSports: string;
        Fencing: string;
        Fishing: string;
        FunctionalStrengthTraining: string;
        Golf: string;
        Gymnastics: string;
        Handball: string;
        Hiking: string;
        Hockey: string;
        Hunting: string;
        Lacrosse: string;
        MartialArts: string;
        MindAndBody: string;
        PaddleSports: string;
        Play: string;
        PreparationAndRecovery: string;
        Racquetball: string;
        Rowing: string;
        Rugby: string;
        Running: string;
        Sailing: string;
        SkatingSports: string;
        SnowSports: string;
        Soccer: string;
        Softball: string;
        Squash: string;
        StairClimbing: string;
        SurfingSports: string;
        Swimming: string;
        TableTennis: string;
        Tennis: string;
        TrackAndField: string;
        TraditionalStrengthTraining: string;
        Volleyball: string;
        Walking: string;
        WaterFitness: string;
        WaterPolo: string;
        WaterSports: string;
        Wrestling: string;
        Yoga: string;
        Barre: string;
        CoreTraining: string;
        CrossCountrySkiing: string;
        DownhillSkiing: string;
        Flexibility: string;
        HighIntensityIntervalTraining: string;
        JumpRope: string;
        Kickboxing: string;
        Pilates: string;
        Snowboarding: string;
        Stairs: string;
        StepTraining: string;
        WheelchairWalkPace: string;
        WheelchairRunPace: string;
        TaiChi: string;
        MixedCardio: string;
        HandCycling: string;
    };
};
export default HealthKit;
